service: rds-ai-trigger-function

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-1
  role: arn:aws:iam::699475917025:role/rds-ai-trigger-lambda-role
  environment:
    DB_SECRET_ID: psw-db-staging-secret


plugins:
  - serverless-python-requirements

functions:
  processRDSEvent:
    handler: handler.lambda_handler
    timeout: 60
    events:
      - sns:
          arn: arn:aws:sns:ap-southeast-1:699475917025:rds-ai-trigger-topic
          topicName: rds-ai-trigger-topic

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    slim: true
    noDeps:
      - boto3
      - botocore
    pipCmdExtraArgs:
      - --no-cache-dir

package:
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - '!.venv/**'
    - '!tests/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!*.pyc'
    - '!**/__pycache__/**'
    - '!**/*.dist-info/**'
