"""Added amount_spent column to Projects table

Revision ID: 2ac334fe53fa
Revises: aaef764d9508
Create Date: 2025-06-27 21:49:46.841108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac334fe53fa'
down_revision: Union[str, None] = 'aaef764d9508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('amount_spent', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Project', 'amount_spent')
    # ### end Alembic commands ###
