"""initialized base schema

Revision ID: 386bdc008262
Revises: 278522bd8d59
Create Date: 2025-06-14 21:32:56.527103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386bdc008262'
down_revision: Union[str, None] = '278522bd8d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('AIInsight',
    sa.Column('insight_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('generated_text', sa.String(), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('Receipt',
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_table('Item',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['Receipt.receipt_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.drop_constraint('User_email_key', 'User', type_='unique')
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.create_unique_constraint('User_email_key', 'User', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_table('Item')
    op.drop_table('Receipt')
    op.drop_table('AIInsight')
    op.drop_table('Project')
    # ### end Alembic commands ###
