"""Added Creation Date column in AI Insights Table

Revision ID: aaef764d9508
Revises: 386bdc008262
Create Date: 2025-06-24 14:25:11.239941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaef764d9508'
down_revision: Union[str, None] = '386bdc008262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIInsight', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AIInsight', 'created_at')
    # ### end Alembic commands ###
